### ISSUE TITLE
CDK 0.25.1

### ISSUE THREAD

**Issue by SpainTrain** [cloudcomponents/jest-cdk-snapshot#1]
Is it possible to get a new release with dependency on 0.25.1?  Based on the breaking changes, it should not require a code change (https://github.com/awslabs/aws-cdk/releases/tag/v0.25.0). Thanks!

**Comment by hupe1980** [comment]
I have updated the dependency...

**Comment by SpainTrain** [comment]
:+1: 	 Thanks for the quick turnaround!  We love using snapshots with CDK stacks, BTW.  Nice elegant approach here.
