### ISSUE TITLE
Support yaml output for snapshots

### ISSUE THREAD

**Issue by inakianduaga** [cloudcomponents/jest-cdk-snapshot#2]
It would be great for quick inspection of snapshots if the output could be YAML instead of JS object. This could be done by converting the output to YAML w/ `js-yaml` before comparing.

Are you open to a PR?

**Comment by hupe1980** [comment]
That sounds good. Pull requests are always welcome.

**Comment by inakianduaga** [comment]
I took a swing at it and the core implementation is trivial

```ts
type OwnOptions = {
  /**
   * Whether to output jest snapshots into YAML instead of JSON, for easier readability
   */
  outputYaml?: boolean
}

const toMatchCdkSnapshot = function(
  this: any,
  received: Stack,
  options: SynthesisOptions & OwnOptions= {}
) {
  const matcher = toMatchSnapshot.bind(this);
  return matcher(convertStack(received, options));
};

const convertStack = (stack: Stack, options: SynthesisOptions & OwnOptions = {}) => {
  const { root } = stack.node;
  const { outputYaml, ...synthOptions } = options

  const assembly = ConstructNode.synth(root.node, synthOptions);
  const template = assembly.getStack(stack.stackName).template;

  return outputYaml ? jsYaml.safeDump(template) : template
};
```

However the way you defined the interface is a bit strange. You have 

```ts
declare global {
  namespace jest {
    interface Matchers<R> {
      toMatchCdkSnapshot(): R;
    }
  }
}
```

which doesn't take any options, yet your actual method does. So not sure what you want to do in order to pass the YAML config. Couple of options:

- Move this to a global jest config for the package and read it from there (not sure how to read the global jest config programatically because it can live in package.json, jest.config.js, etc, but there should be a way
- Hardcode it to YAML and not make it an option
- Switch `toMatchCdkSnapshot(): R;` exposed type to accept options, and refactor your function

**Comment by hupe1980** [comment]
Oh that's a bug! This would be right:

```typescript
declare global {
    namespace jest {
        interface Matchers<R> {
            toMatchCdkSnapshot(options?: SynthesisOptions): R;
        }
    }
```
}
Then you can specify the parameter when calling the function

**Comment by hupe1980** [comment]
@inakianduaga I've fixed the issue

**Comment by inakianduaga** [comment]
thanks, take a look 

https://github.com/cloudcomponents/jest-cdk-snapshot/pull/3
